// ── Rust-derived types — generated by ts-rs, re-exported for consumers ────────
export type { LaunchScope }     from '../bindings/LaunchScope'
export type { LaunchedInfo }    from '../bindings/LaunchedInfo'
export type { SessionDto }      from '../bindings/SessionDto'
export type { WorkspaceInfo }   from '../bindings/WorkspaceInfo'
export type { DocEntry }        from '../bindings/DocEntry'
export type { ArchEntityDto }   from '../bindings/ArchEntityDto'
export type { ArchCatalogDto }  from '../bindings/ArchCatalogDto'
export type { SaveEntityArgs }  from '../bindings/SaveEntityArgs'
export type { ScopeTreeRepo }   from '../bindings/ScopeTreeRepo'
export type { ScopeTreeProject }  from '../bindings/ScopeTreeProject'
export type { ScopeTreeTenant }   from '../bindings/ScopeTreeTenant'
export type { ScopeTreeWorkspace } from '../bindings/ScopeTreeWorkspace'
export type { HarnessLayer }         from '../bindings/HarnessLayer'
export type { HarnessMcpServer }     from '../bindings/HarnessMcpServer'
export type { HarnessInstruction }   from '../bindings/HarnessInstruction'
export type { HarnessEnvVar }        from '../bindings/HarnessEnvVar'
export type { HarnessCommand }       from '../bindings/HarnessCommand'
export type { HarnessHook }          from '../bindings/HarnessHook'
export type { HarnessPluginContext } from '../bindings/HarnessPluginContext'
export type { HarnessScopeInfo }     from '../bindings/HarnessScopeInfo'
export type { HarnessReport }        from '../bindings/HarnessReport'
export type { PluginInfo }      from '../bindings/PluginInfo'
export type { DaemonStatus }    from '../bindings/DaemonStatus'

// ── UI-only types — no Rust equivalent ────────────────────────────────────────

import type { SessionDto } from '../bindings/SessionDto'

// Session extends the Rust-generated SessionDto and adds `status` (UI-only annotation).
// is_history is marked optional because the backend omits it when false.
export interface Session extends Omit<SessionDto, 'is_history'> {
  is_history?: boolean
  status?: 'working' | 'ready'
}

export interface Tab {
  id: string
  title: string
  type?: 'terminal' | 'shortcuts' | 'uikit' | 'colors' | 'settings' | 'document' | 'architecture' | 'ui-map' | 'task' | 'feature-page'
  sessionId?: string
  tmuxSession?: string
  docId?: string
  archWorkspace?: string
  archTenant?: string
  taskId?: string
  /** Only on type === 'feature-page': which nav view this page belongs to */
  featureView?: NavView
}

// ── Task types ─────────────────────────────────────────────────────────────────

export type TaskStatus = 'todo' | 'in_progress' | 'done' | 'blocked' | 'cancelled'
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical'
export type TaskSource =
  | { type: 'manual' }
  | { type: 'plugin'; name: string; external_id: string; url?: string }

export interface OrbitTask {
  id: string
  title: string
  description?: string
  status: TaskStatus
  priority: TaskPriority
  task_type?: string
  source: TaskSource
  workspace: string
  tenant?: string
  project?: string
  repository?: string
  tags: string[]
  created_at: number
  updated_at: number
}

export type NavView =
  | 'terminal'
  | 'tasks'
  | 'plans'
  | 'plugins'
  | 'mcps'
  | 'activity'
  | 'documents'
  | 'architecture'
  | 'settings'
  | 'profile'
  | 'docs'

export type SettingCategory = 'general' | 'appearance' | 'terminal' | 'engine' | 'privacy'
export type SettingType = 'boolean' | 'string' | 'number' | 'select'

export interface SettingOption { label: string; value: string }

export interface Setting {
  id: string
  category: SettingCategory
  key: string
  name: string
  description: string
  type: SettingType
  value: boolean | string | number
  default: boolean | string | number
  options?: SettingOption[]
}

export type Theme = 'dark' | 'light'
export type ShortcutCategory = 'navigation' | 'terminal' | 'app'

export interface Shortcut {
  id: string
  name: string
  description: string
  keys: string
  action: string
  category: ShortcutCategory
  builtin: boolean
}

// ── TS-only type aliases ───────────────────────────────────────────────────────
export type ArchLayout = Record<string, [number, number]>
export type ArchRoutes = Record<string, Record<string, number>>

// ── Updates / CLI types ────────────────────────────────────────────────────────

export interface CliInfo {
  installed: boolean
  version: string | null
  path: string | null
}

export interface ComponentUpdate {
  current: string | null
  latest: string | null
  has_update: boolean
}

export interface UpdateCheck {
  cli: ComponentUpdate
  desktop: ComponentUpdate
}
